# Nom du fichier : crowdsec.conf

# Technologie : Zabbix Agent 2 / CrowdSec

# Catégorie : Supervision / Sécurité

# Auteur : Cybersecurity-Learning-Lab

# Objectif : Exposer à Zabbix des informations permettant de superviser l'état de CrowdSec et de sa LAPI sur la VM Zabbix.

# Version : 1.0

# Dernière modification : 11/08/2026

# CrowdSec monitoring via Zabbix Agent 2

UserParameter=crowdsec.metrics.raw,/usr/bin/cscli metrics -o json 2>/dev/null

UserParameter=crowdsec.lapi.status,cscli lapi status >/dev/null 2>&1 && echo 1 || echo 0
